package edu.csumb.spring19.capstone.models.dbfilter;

import java.util.List;

import edu.csumb.spring19.capstone.models.card.Card;

public class DbFilterResponse {
    private List<Card> cards;
    // The number of cards generated by the filter, before pagination (sublist / limit) is implement.
    private int size;

    public DbFilterResponse(List<Card> list, int size) {
        this.cards = list;
        this.size = size;
    }

    public List<Card> getCards() {
        return this.cards;
    }

    public void setCards(List<Card> cards) {
        this.cards = cards;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }
}
